import { readdir, readFile } from "node:fs/promises";
import { join } from "node:path";
import type { GraderResult } from "../types.js";

/**
 * LLM-based rubric grading.
 * Evaluates each criterion as PASS/FAIL using an LLM with structured output.
 *
 * Follows the verify/classifier/llm.ts pattern:
 * - Dynamic imports to avoid module-level evaluation issues
 * - Returns a skip result (not failure) when no LLM provider is available
 * - Never throws for missing API keys
 */
export async function gradeLlmRubric(
	workDir: string,
	criteria: string[],
	rubricPath?: string,
	prompt?: string,
	providerFlag?: string,
	modelFlag?: string
): Promise<GraderResult> {
	try {
		// Dynamic imports to avoid module-level evaluation issues
		const { resolveModel } = await import("../../llm/providers.js");
		const { generateObject } = await import("ai");
		const { z } = await import("zod");

		const model = await resolveModel(providerFlag, modelFlag);

		// Build file list from workDir
		let fileList: string[] = [];
		try {
			fileList = await listFilesRelative(workDir);
		} catch {
			// Cannot list files, continue with empty list
		}

		// Read file contents for evaluation context
		const fileContents: Record<string, string> = {};
		for (const f of fileList.slice(0, 10)) {
			try {
				const content = await readFile(join(workDir, f), "utf-8");
				// Limit per-file content to 4000 chars
				fileContents[f] =
					content.length > 4000 ? `${content.slice(0, 4000)}\n... (truncated)` : content;
			} catch {
				// skip unreadable files
			}
		}

		// Load rubric template if provided
		let rubricText = "";
		if (rubricPath) {
			try {
				rubricText = await readFile(rubricPath, "utf-8");
			} catch {
				// Rubric file not found, use default
			}
		}

		// Template variable substitution
		const fileListStr = fileList.join(", ");
		rubricText = rubricText
			.replace(/\{\{prompt\}\}/g, prompt ?? "")
			.replace(/\{\{file_list\}\}/g, fileListStr)
			.replace(/\{\{product_version\}\}/g, "");

		const RubricSchema = z.object({
			criteria: z.array(
				z.object({
					criterion: z.string(),
					passed: z.boolean(),
					explanation: z.string(),
				})
			),
		});

		const systemPrompt =
			rubricText ||
			`You are evaluating code generated by an AI agent.
Score each criterion as PASS or FAIL with a brief explanation.
Be strict but fair.`;

		const filesSection = Object.entries(fileContents)
			.map(([name, content]) => `### ${name}\n\`\`\`\n${content}\n\`\`\``)
			.join("\n\n");

		const userPrompt = `Evaluate the following criteria for the generated code:

## Criteria to evaluate
${criteria.map((c, i) => `${i + 1}. ${c}`).join("\n")}

## Files produced
${filesSection || "(no files)"}

## Agent prompt
${prompt ?? "(not provided)"}

For each criterion, determine if it PASSES or FAILS and explain why.`;

		const { object: result } = await generateObject({
			model,
			schema: RubricSchema,
			system: systemPrompt,
			prompt: userPrompt,
		});

		const passed = result.criteria.every((c) => c.passed);
		const failedCriteria = result.criteria.filter((c) => !c.passed);
		const detail = result.criteria
			.map((c) => `${c.passed ? "PASS" : "FAIL"}: ${c.criterion} — ${c.explanation}`)
			.join("\n");

		return {
			grader: "llm-rubric",
			passed,
			message: passed
				? `All ${criteria.length} criterion/criteria passed LLM evaluation`
				: `${failedCriteria.length} of ${criteria.length} criterion/criteria failed LLM evaluation`,
			detail,
		};
	} catch {
		// No LLM provider available, or LLM call failed — gracefully degrade
		return {
			grader: "llm-rubric",
			passed: true,
			message: `LLM rubric grading skipped (no LLM provider available) — ${criteria.length} criterion/criteria not evaluated`,
			detail: "Skipped: LLM provider not configured or unavailable",
		};
	}
}

async function listFilesRelative(dir: string, prefix = ""): Promise<string[]> {
	const files: string[] = [];
	const entries = await readdir(dir, { withFileTypes: true });

	for (const entry of entries) {
		const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
		if (entry.isDirectory()) {
			const nested = await listFilesRelative(join(dir, entry.name), relative);
			files.push(...nested);
		} else {
			files.push(relative);
		}
	}

	return files;
}
